---
title: "FIN 302 Project:  Tolling Agreement Valuation"
author:  "Matt Brigida, Ph.D."
---

## Power Plant and Data

Power Plant Name:  CALPINE_BP_GT1  (meaning Calpine Corporation's, Beth Page Location, Gas Turbine Number 1)
Power Plant PTID:  23823

Link to data for all days in June 2018: [http://mis.nyiso.com/public/csv/realtime/20180601realtime_gen_csv.zip](http://mis.nyiso.com/public/csv/realtime/20180601realtime_gen_csv.zip)


## Overview 

Value the following tolling contract on a natural gas fired power plant via discounted cash flows.  You will turn in an Excel file with your calculations. A well-organized spreadsheet should allow me to change some of your assumptions to see the effect on the contract value.  Within the spreadsheet in a text box, you should supply a couple of paragraphs explaining your assumptions and methodology.  You should also supply your level of confidence in your estimates (you can do this in Monte Carlo fashion by varying the inputs and observing your range of contract values).

### Contract Details:

#.  Your contract is for 250 MW per hour, for every on-peak hour from 6/10/2019 to 6/14/2019 (inclusive of start and end dates).
#.  Note on-peak means 5x16, or Monday through Friday from the hour ending 0800 to the hour ending 2300.
#.  The plant's heat rate (HR) is: 7.1.
#.  The contract states, for each day you choose to produce electricity, you'll pay the day's Henry Hub spot natural gas price plus \$0.17.
#.  You will receive the real-time wholesale electricity price at the plant's PnodeID.
#.  For each MWh you choose to produce, you'll pay a operating fee of \$0.45.  You won't have to pay any other costs such as those for starting up the plant (if necessary).
#.  For each day you can either produce 250 MW per hour or nothing.  Therefore for each day you will produce 16*250 = 4000 MWh or 0 MWh. 
#.  You must notify the plant by 6pm if you plan to run the plant the following day. 
#. For one day only in the interval 6/10/2019 to 6/14/2019, you have the right to produce an extra 350MW per hour during the on-peak hours. Once you exercise this right on a particular day, the right ceases to exist.

To get you started, the plant's HR (a measure of efficiency) is defined as the number of British thermal units (Btu) of input fuel required to generate 1 megawatt hour (MWh) of electricity.  Thus, for a particular plant, the heat rate can be written as $HR=\frac{S_E}{S_G}MMBtu/MWh$ where $S_E$ and $S_G$ denote the spot price of electricity and natural gas respectively. 

Given the HR, the cash flow from the opportunity to generate 1 MWh of electricity at some point in the future (denoted by $T$) may be written as $CF=max(S^T_E-(HR)S^T_G, \;0)$ where $CF$ denotes cash flow.  Remember, you are producing 250 MW per hour and not 1.  Also note, I have not taken into account other factors such as your operating fee, and your basis from Henry Hub.

